### PR TITLE
Added classes to CommonsMath3's PrecisionRecall test and added direct translations

### PR DESCRIPTION
**Pull request by khaeghar**
## Added classes to the PrecisionRecall test of CommonsMath3
- Line
- SubLine
- BigFraction
- Fraction (This .json read fails. Log at the end)
- Vector3D
- S2Point

## Added direct translations for:
- "smaller than", "smaller than or equal to"
- "strictly positive", "strictly negative"

Checked in my class: 
```
[main] TRACE org.toradocu.translator.ConditionTranslator - Identifying propositions from: "if myvar is strictly positive" in Test1(java.lang.Integer myvar,java.lang.Integer myvares)
done [1.5 sec].
[main] TRACE org.toradocu.translator.ConditionTranslator - Translated proposition (myvar, is positive) as: args[0]>0
[main] TRACE org.toradocu.translator.ConditionTranslator - Identifying propositions from: "if myvar is strictly negative" in Test2(java.lang.Integer myvar,java.lang.Integer myvares)
[main] TRACE org.toradocu.translator.ConditionTranslator - Translated proposition (myvar, is negative) as: args[0]<0
[main] TRACE org.toradocu.translator.ConditionTranslator - Identifying propositions from: "if myvar is smaller than 3" in Test3(java.lang.Integer myvar,java.lang.Integer myvares)
[main] TRACE org.toradocu.translator.ConditionTranslator - Translated proposition (myvar, is < 3) as: args[0]<3
[main] TRACE org.toradocu.translator.ConditionTranslator - Identifying propositions from: "if myvar is smaller than or equal to 3" in Test4(java.lang.Integer myvar,java.lang.Integer myvares)
[main] TRACE org.toradocu.translator.ConditionTranslator - Translated proposition (myvar, is <= 3) as: args[0]<=3
/home/sergio/Toradocu/Test.json:40: "comment": "if myvar is strictly positive",
/home/sergio/Toradocu/Test.json:41: "condition": "args[0]>0"

/home/sergio/Toradocu/Test.json:84: "comment": "if myvar is strictly negative",
/home/sergio/Toradocu/Test.json:85: "condition": "args[0]<0"

/home/sergio/Toradocu/Test.json:128: "comment": "if myvar is smaller than 3",
/home/sergio/Toradocu/Test.json:129: "condition": "args[0]<3"

/home/sergio/Toradocu/Test.json:172: "comment": "if myvar is smaller than or equal to 3",
/home/sergio/Toradocu/Test.json:173: "condition": "args[0]<=3"

[main] INFO org.toradocu.generator.OracleGenerator - Oracle generator disabled: skipped aspect generation.
```

Log of Fraction in JUnit test:
```
fractionTest(org.toradocu.PrecisionRecallCommonsMath3)
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 2 column 4 path $
	at com.google.gson.Gson.fromJson(Gson.java:899)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at org.toradocu.testlib.PrecisionRecallTest.compare(PrecisionRecallTest.java:91)
	at org.toradocu.testlib.PrecisionRecallTest.computePrecisionAndRecall(PrecisionRecallTest.java:64)
	at org.toradocu.testlib.AbstractPrecisionRecallTestSuite.computePrecisionAndRecall(AbstractPrecisionRecallTestSuite.java:93)
	at org.toradocu.testlib.AbstractPrecisionRecallTestSuite.test(AbstractPrecisionRecallTestSuite.java:108)
	at org.toradocu.PrecisionRecallCommonsMath3.fractionTest(PrecisionRecallCommonsMath3.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 2 column 4 path $
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	... 31 more 
```

### CODE REVIEW

**Comment by mernst** [comment]
The build failed; see https://travis-ci.org/albertogoffi/toradocu/builds/170100264#L3212 .

Could you fix this?

If it isn't easy to determine what failed, then we should consider making the JUnit output more descriptive rather than pointing at a .html fille.

**Comment by khaeghar** [comment]
Now the only test that fails is the Fraction one, but I don't know why. It seems that the .json is not correct (Don't know which one, if the generated or the expected one)

**Comment by mernst** [comment]
Now the build is broken for everyone: https://travis-ci.org/albertogoffi/toradocu/builds/170105856 .
Can you please fix this?

In the future, if a test is failing, please do not merge the pull request.
More generally, we expect someone other than the author to merge pull requests.

**Comment by albertogoffi** [comment]
Collaborators can merge pull requests into the master branch, but please do not merge them, especially if the build fails.

In general, I'd like to maintain the control of the codebase and merge pull requests.

About the issue, I'm going to investigate the problem related with the test on the class Fraction.

**Comment by khaeghar** [comment]
Oh, sorry for that, didn't know that the merge was on the main branch of
alberto, thought was on mine.

2016-10-24 14:08 GMT+02:00 Alberto Goffi <notifications@github.com>:

**Pull request merged**
