### PR TITLE
Manual POStagging and more improvements

### PR DESCRIPTION
**Pull request by ariannab**
This request includes:
- the code for the manual POStagging of code elements (as nouns) and inequalities' placeholders (as adjectives)
- some other small improvements: more precise variable comparison and support for floating point numbers (to translate conditions like `args[0]>1.0`)
- fix in preicsion/recall test suite and in some goal files

### CODE REVIEW

**Comment by ariannab** [comment]
2 tests are failing (all right on my machine, but my branch is 7 commits behind master).

**Comment by albertogoffi** [comment]
I'm going to check whether the tests fail also on my machine.

**Comment by albertogoffi** [comment]
Also on my machine none of our tests fails.

Failing test cases on Travis are:
```
org.toradocu.PrecisionRecallCommonsCollections4 > testAnyPredicate FAILED
    java.lang.AssertionError at PrecisionRecallCommonsCollections4.java:81

org.toradocu.PrecisionRecallCommonsCollections4 > testAllPredicate FAILED
    java.lang.AssertionError at PrecisionRecallCommonsCollections4.java:71
```

@ariannab is it possible that the changes in this PR (#108) introduce non-determinism that manifests in those two tests?

**Comment by albertogoffi** [comment]
Resubmitted as #110 to have a more clean history.

**Pull request closed without merging**
