### PR TITLE
Added 'instanceof' into the comparator's list

### PR DESCRIPTION
**Pull request by khaeghar**

### CODE REVIEW

**Comment by albertogoffi** [comment]
Hi Sergio,

Could you add test cases to the Toradocu test suite, so that we know that your changes are correctly working and we can have a measure of the impact of those?

I will merge the pull request when you will add the tests.

Thanks.

**Comment by mernst** [comment]
Building on Alberto's comment, that will also ensure that no one breaks your enhancements in the future.  Thanks!

**Comment by khaeghar** [comment]
Yeah, sure. The thing is that the test cases are "home made"
The only example that I have from CommonsMath3 is already on the test case
of CommonsMath3, in the examples that I added.
Anyway, if I want to add my test cases into Toradocu, where should I add
those examples? In a new file? Added into any of the test for the
ConditionTranslator?

**Comment by mernst** [comment]
If there is an example in CommonsMath3, that's good.  I don't see any changes to the Toradocu test suite's expected output in this pull request, however.

**Comment by khaeghar** [comment]
Because when I created the expected output for the BinaryMutation, I'd
written the .json as Toradocu had to translate it. So the expected output
for that class is already the correct one. (Maybe I'm not understanding the
problem. If it's not this, I apologize)

**Comment by mernst** [comment]
Does this mean that the test suite failed until this commit?  That's what I would expect if the output of Toradocu had changed and the new output is correct.  I'm not seeing that in Travis.

**Comment by khaeghar** [comment]
It matches both of the throws tag in that class (The empty one and the
instanceof one). The thing is that the value for the PrecisionRecall test
is wrong (Maybe that's the fail :S) that is 0.5 instead of 1

2016-10-13 22:51 GMT+02:00 Michael Ernst <notifications@github.com>:

**Comment by albertogoffi** [comment]
Can you confirm that the test `org.toradocu.PrecisionRecallCommonsMath3.binaryMutationTest` fails because Toradocu recall is no longer 0.5 but 1.0? It's strange that the build is still passing on Travis without changing the value of the assertion about the recall from 0.5 to 1.0. Maybe the test suite `org.toradocu.PrecisionRecallCommonsMath3` was disabled when the build ran on Travis?

**Comment by khaeghar** [comment]
Yes, when I ran the test on my computer with the changes, the Precision
Recall test changed to 1.0 passed

**Comment by albertogoffi** [comment]
> Yes, when I ran the test on my computer with the changes, the PrecisionRecall test changed to 1.0 passed

Perfect. Can you modify the assertion in the test suite (0.5->1.0) and integrate the change in the pull request?

**Comment by khaeghar** [comment]
Yeah, done, :D!

**Pull request merged**
